[package]
name = "coco-map"
version = "0.1.0"
authors = ["Yi-Hung Kuo <r09922027@csie.ntu.edu.tw>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
