[package]
name = "yolo-dl"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.1"
failure = "0.1"
noisy_float = { version = "0.1", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
