[workspace]
members = [
    "yolo-dl",
    "train",
    "darknet-config",
    # "darknet-test",
    "tch-goodies",
    "model-config",
    "yolo-dl-doc",
]

[profile.release]
debug = true
debug-assertions = true
overflow-checks = true

[patch.crates-io]
serde_ini = { git = "https://github.com/jerry73204/serde-ini.git", branch = "enum-support" }
