[package]
name = "yolo-dl"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.1"
noisy_float = { version = "0.1", features = ["serde-1"] }
serde = { version = "1.0", features = ["derive"] }
itertools = "0.9"
tch-tensor-like = { git = "https://github.com/jerry73204/tch-tensor-like.git", features = ["derive"] }
anyhow = "1.0"
approx = "0.3"
derive_more = "0.99"
unzip-n = "0.1"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-std = { version = "1.6", features = ["unstable", "attributes"] }
coco = { git = "https://github.com/jerry73204/coco-rs.git", features = ["async"] }
argh = "0.1"
json5 = "0.2"
par-stream = { git = "https://github.com/jerry73204/par-stream.git" }
futures = "0.3"
rand = "0.7"
percent-encoding = "2.1"
image = "0.23"
tokio = { version = "0.2", features = ["sync"] }
tfrecord = { version = "0.3", features = ["full"] }
ndarray = "0.13"
log = "0.4"
pretty_env_logger = "0.4"
tch-serde = "0.1.2"

[patch.crates-io]
tch = { git = "https://github.com/LaurentMazare/tch-rs.git" }
tfrecord = { git = "https://github.com/jerry73204/rust-tfrecord.git", branch = "tch-with-anyhow" }
