[package]
name = "label"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bbox = { version = "0.1.0", path = "../bbox" }
num-traits = "0.2.14"
