[package]
name = "train"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3"
noisy_float = { version = "0.1", features = ["serde-1", "approx"] }
serde = { version = "1.0", features = ["derive"] }
itertools = "0.9"
tch-tensor-like = { version = "0.2", features = ["derive"] }
anyhow = "1.0"
approx = "0.4"
derive_more = "0.99"
unzip-n = "0.1"
serde_json = "1.0"
async-std = { version = "1.8", features = ["unstable", "attributes"] }
coco = { git = "https://github.com/jerry73204/coco-rs.git", features = ["async"] }
json5 = "0.2"
par-stream = "0.2"
futures = "0.3"
rand = "0.7"
percent-encoding = "2.1"
image = "0.23"
tokio = { version = "1.0", features = ["sync"] }
tfrecord = { version = "0.5", features = ["full"] }
ndarray = "0.13"
tch-serde = "0.3"
chrono = "0.4"
uuid = { version = "0.8", features = ["v4"] }
regex = "1.3"
indexmap = "1.6"
glob = "0.3"
num_cpus = "1.13"
voc-dataset = "0.2"
serde-xml-rs = "0.4"
# xz2 = { version = "0.1", features = ["tokio-io", "futures"] }
tch-goodies = { version = "0.1", path = "../tch-goodies" }
yolo-dl = { version = "0.1", path = "../yolo-dl" }
mmap-dataset = { version = "0.1", path = "../mmap-dataset" }
rand_distr = "0.3"
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
structopt = "0.3"
model-config = { version = "0.1", path = "../model-config" }
darknet-config = { version = "0.1", path = "../darknet-config" }

[features]
profiling = ["yolo-dl/profiling"]
