[package]
name = "tch-goodies"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tch = "0.3"
itertools = "0.9"
image = "0.23"
noisy_float = { version = "0.1", features = ["serde-1", "approx"] }
serde = { version = "1.0", features = ["derive"] }
tch-tensor-like = { version = "0.2", features = ["derive"] }
approx = "0.4"
log = "0.4"
maplit = "1.0"
getset = "0.1"
unzip-n = "0.1"
rand = "0.7"
