[package]
name = "tch-goodies"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
tch = "0.3.1"
itertools = "0.10.0"
image = "0.23.12"
noisy_float = { version = "0.1.13", features = ["serde-1", "approx"] }
serde = { version = "1.0.119", features = ["derive"] }
tch-tensor-like = { version = "0.2.0", features = ["derive"] }
approx = "0.3.2"
getset = "0.1.1"
unzip-n = "0.1.2"
