[package]
name = "tch-modules"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.44"
approx = "0.5.0"
cv-convert = { version = "0.12.0", default-features = false, features = ["tch", "ndarray"] }
getset = "0.1.1"
image = "0.23.14"
itertools = "0.10.1"
log = "0.4.14"
mona = "0.1.0"
ndarray = "0.15.3"
noisy_float = { version = "0.2.0", features = ["serde", "approx"] }
num-traits = "0.2.14"
serde = { version = "1.0.130", features = ["derive"] }
tch = "0.5.0"
tch-tensor-like = { version = "0.4.0", features = ["derive"] }
unzip-n = "0.1.2"
model-graph = { version = "0.1.0", path = "../model-graph" }
tch-goodies = { version = "0.1.0", path = "../tch-goodies" }
strum = "0.21.0"
derivative = "2.2.0"

[dev-dependencies]
rand = "0.8.4"
