[package]
name = "yolo-dl"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.1"
noisy_float = { version = "0.1.13", features = ["serde-1", "approx"] }
serde = { version = "1.0.119", features = ["derive"] }
itertools = "0.10.0"
tch-tensor-like = { version = "0.2.0", features = ["derive"] }
anyhow = "1.0.38"
approx = "0.4.0"
unzip-n = "0.1.2"
serde_json = "1.0.61"
async-std = { version = "1.8.0", features = ["unstable", "attributes"] }
coco = { git = "https://github.com/jerry73204/coco-rs.git", features = ["async"] }
argh = "0.1.4"
par-stream = "0.2.1"
futures = "0.3.10"
rand = "0.8.2"
percent-encoding = "2.1.0"
tokio = { version = "1.0.1", features = ["sync"] }
tfrecord = { version = "0.5.0", features = ["full"] }
ndarray = "0.13.0"
log = "0.4.13"
chrono = "0.4.19"
uuid = { version = "0.8.2", features = ["v4"] }
regex = "1.4.3"
indexmap = "1.6.1"
num_cpus = "1.13.0"
# xz2 = { version = "0.1", features = ["tokio-io", "futures"] }
tch-goodies = { version = "0.1", path = "../tch-goodies" }
lazy_static = "1.4.0"
envy = "0.4.2"
dashmap = "4.0.2"
slice-of-array = "0.2.1"
getset = "0.1.1"
model-config = { version = "0.1", path = "../model-config" }
petgraph = "0.5.1"
derivative = "2.1.3"

[features]
profiling = []
