[package]
name = "model-config"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
noisy_float = { version = "0.1.13", features = ["serde-1", "approx"] }
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
indexmap = { version = "1.6.1", features = ["serde-1"] }
derivative = "2.1.3"
structopt = "0.3.21"
json5 = "0.3.0"
itertools = "0.10.0"
petgraph = "0.5.1"
take_mut = "0.2.2"
unzip-n = "0.1.2"
strum = { version = "0.20.0", features = ["derive"] }
dot = { version = "0.1.4", optional = true }
getset = "0.1.1"
prettytable-rs = "0.8.0"

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = ["dot"]
